apiVersion: batch/v1
kind: Job
metadata:
  name: node-app-load-job
  namespace: nginx
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: load
        image: busybox
        command:
        - sh
        - -c
        - |
          # loop to generate sustained load; stop by deleting the Job
          while true; do
            wget -q -O- http://notes-app-service.nginx.svc.cluster.local:8000 >/dev/null
            sleep 0.1
          done
      restartPolicy: Never
